// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/subscribe": {
            "post": {
                "description": "Add a subscription information into database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "CreateSubscription",
                "operationId": "create-subscription",
                "parameters": [
                    {
                        "description": "Subscription main info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subsApp.Subscription"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.successNewSubMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/subscribe/all": {
            "get": {
                "description": "Get information about all subscriptions from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "GetAllSubscriptions",
                "operationId": "get-all-subscriptions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subsApp.SubscriptionJSON"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/subscribe/sum": {
            "get": {
                "description": "Get the total cost of all subscriptions for a selected period, filtered by user ID and subscription name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "GetSubsCostSum",
                "operationId": "get-total-cost-sum-subscriptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service name",
                        "name": "service_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date from",
                        "name": "date_from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date to",
                        "name": "date_to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.totalCostSum"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/subscribe/{id}": {
            "get": {
                "description": "Get a subscription information from database by its id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "GetSubscription",
                "operationId": "get-subscription",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subsApp.SubscriptionJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "Update subscription information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "UpdSubscription",
                "operationId": "upd-subscription",
                "parameters": [
                    {
                        "description": "Subscription updated info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subsApp.UpdSubscription"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.emptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove subscription information from database by subscription id",
                "tags": [
                    "subscriptions"
                ],
                "summary": "DeleteSubscription",
                "operationId": "del-subscription",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.emptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.emptyResponse": {
            "type": "object"
        },
        "handler.errorMsg": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "handler.successNewSubMsg": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.totalCostSum": {
            "type": "object",
            "properties": {
                "sum": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "subsApp.Subscription": {
            "type": "object",
            "required": [
                "price",
                "service_name",
                "start_date",
                "user_id"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "07-2021"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer",
                    "example": 1000
                },
                "service_name": {
                    "type": "string",
                    "example": "Web Hosting"
                },
                "start_date": {
                    "type": "string",
                    "example": "06-2020"
                },
                "user_id": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        },
        "subsApp.SubscriptionJSON": {
            "type": "object",
            "required": [
                "price",
                "service_name",
                "start_date",
                "user_id"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "07-2021"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer",
                    "example": 1000
                },
                "service_name": {
                    "type": "string",
                    "example": "Web Hosting"
                },
                "start_date": {
                    "type": "string",
                    "example": "06-2020"
                },
                "user_id": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        },
        "subsApp.UpdSubscription": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "07-2021"
                },
                "price": {
                    "type": "integer",
                    "example": 1000
                },
                "service_name": {
                    "type": "string",
                    "example": "Web Hosting"
                },
                "start_date": {
                    "type": "string",
                    "example": "06-2020"
                },
                "user_id": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Subs App API",
	Description:      "API Server for SubsApp Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
